<?php

// Load includes
module_load_include('inc', 'ng_blocks', 'includes/ng_blocks.preprocess');

// Implements hook_block_info()
function ng_blocks_block_info() {
  $blocks = array();
  $blocks['ng_header'] = array(
    'info' => t('NG Header block'),
  );
  $blocks['ng_guide_listing'] = array(
    'info' => t('NG Guide listing'),
  );
  $blocks['ng_guide_authors'] = array(
    'info' => t('NG Guide authors'),
  );
  return $blocks;
}

// Implements hook_block_view()
function ng_blocks_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'ng_header':
      $block['subject'] = t('NG Header');
      $block['content'] = theme('ng_header_content');
      break;
      
    case 'ng_guide_listing':
      $block['subject'] = t('NG Guide listing');
      $block['content'] = theme('ng_guide_listing_content');
      break;
      
    case 'ng_guide_authors':
      $block['subject'] = t('NG Guide authors');
      $block['content'] = theme('ng_guide_authors_content');
      break;
  }
  return $block;
}

// Implements hook_theme()
function ng_blocks_theme() {
  $path = drupal_get_path('module', 'ng_blocks') . '/templates';
  return array(
    // Main header block
    'ng_header_content' => array(
      'path' => $path,
      'template' => 'ng-header-content',
      'variables' => array(
        'search' => NULL,
        'logo' => NULL,
        'site_name' => NULL
      )
    ),
    
    // Primary links template that lives in the header
    'ng_header_primary_links' => array(
      'path' => $path,
      'template' => 'ng-header-primary-links',
      'variables' => array()
    ),
    
    // Header user info
    'ng_header_user_info' => array(
      'path' => $path,
      'template' => 'ng-header-user-info',
      'variables' => array()
    ),
    
    // Guide listing content - retrieves content from services views 
    'ng_guide_listing_content' => array(
      'path' => $path,
      'template' => 'ng-guide-listing-content',
      'variables' => array()
    ),
    
    // Guide authors content - retrieves guide authors from services views 
    'ng_guide_authors_content' => array(
      'path' => $path,
      'template' => 'ng-guide-authors-content',
      'variables' => array()
    )
  );
}


function ng_blocks_views_post_execute(&$view) {

}


function ng_blocks_services_views_execute_view_alter(&$output, $view) {
  $paged_output = array(
    'results' => $output,
    'limit' => $view->query->limit,
    'current_page' => $view->query->pager->current_page,
    'total_rows' => $view->total_rows,
  );
  //watchdog('ng_blocks', '<pre>'.print_r($view->query->pager, true).'</pre>');
  $output = $paged_output;
}
